version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      #args:
      #  - GPR_USERNAME=${GPR_USERNAME}
      #  - GPR_TOKEN=${GPR_TOKEN}
      tags:
        - ghcr.io/monash-fit3170/ai_travel_plan/aitravelplannerfrontend:${version}
    image: app
    ports:
      - "3000:3000"
    volumes:
      - "./client/src:/app/src"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      #args:
      #  - GPR_USERNAME=${GPR_USERNAME}
      #  - GPR_TOKEN=${GPR_TOKEN}
      tags:
        - ghcr.io/monash-fit3170/ai_travel_plan/aitravelplannerbackend:${version}
    ports:
      - "4000:4000"
    volumes:
      - "./server/src:/app/src"
    stdin_open: true
    
  tests:
    build:
      context: ./server
      dockerfile: Dockerfile
      #args:
      #  - GPR_USERNAME=${GPR_USERNAME}
      #  - GPR_TOKEN=${GPR_TOKEN}
      target: tests
    image: tests
