version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: app
    ports:
      - "3000:3000"
    volumes:
      - "./client/src:/app/src"
    depends_on:
      - backend
    tags:
      - ghcr.io/Monash-FIT3170/AI_Travel_Plan/aitravelplannerfrontend:${version}

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - "./server/src:/app/src"
    stdin_open: true
    tags:
      - ghcr.io/Monash-FIT3170/AI_Travel_Plan/aitravelplannerbackend:${version}
    
  tests:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: tests
    image: tests
