version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./client/src:/app/src"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - "./server/src:/app/src"
    stdin_open: true
